config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'twerts#index'

  ## UserController routes
  #resources :users  # switched this out for explicit routes for practice
  post 'signup', to: 'users#create'
  get 'signup', to: 'users#signup'

  ## SessionsController routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  ## TwertsController routes
  get 'twerts/:id', to: 'twerts#show', as: :twert
  post 'twerts', to: 'twerts#create'

  ## Likes routes
  post 'likes', to: 'likes#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable, polymorphic: true
	belongs_to :user
end

app/models/twert.rb
class Twert < ApplicationRecord
	belongs_to :user
	belongs_to :parent_twert, class_name: "Twert", optional: true

	has_many :replies, class_name: "Twert", foreign_key: "parent_twert_id"
	has_many :likes, as: :likeable

	validates :user, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	# use bcrypt gem to ensure strong password
	has_secure_password

	has_many :likes
	has_many :user_likes, as: :likeable

	validates :username, presence: true, uniqueness: true
	validates :email, uniqueness: true
	validates :password, presence: true, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method def current_user
		return @current_user if @current_user.present?
		if session[:user_id].present?
			@current_user = User.find(session[:user_id])
		end
	end

	helper_method def likeable_html_id(likeable)
		return "#{likeable.class.name.downcase}_#{likeable.id}" if likeable
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		likeable_id = params[:likeable_id]
		likeable_type = params[:likeable_type]
		user_id = current_user.id

		like = Like.create({ user_id: user_id, likeable_id: likeable_id, likeable_type: likeable_type })

		# real world, we probably don't count every time we create, instead use some kind of caching for counter (counter cache built in rails feature apparently)
		likeable = likeable_class.find(likeable_id)
		like_count = likeable.likes.count

		# one silly way
			# like.likeable.likes.count
		# another silly way
			# could be a problem with constantize being run for any random input
			# likeable_type.constantize.find(likeable_id)

		render json: { message: "success", like_count: like_count }, status: :ok
	end

	private

	def likeable_class
		case params[:likeable_type]
		when "Twert"
			Twert
		when "User"
			User
		else
			head 418	# easy way to give an http response (http status 418 is the joke "i'm a teapot" code)
		end

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(username: params[:username])
		if user.present? && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path, notice: "Welcome back, #{user.username}"
		else
			flash.now[:alert] = "Invalid username or password"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: "Have a safe trip!"
	end
end

app/controllers/twerts_controller.rb
class TwertsController < ApplicationController
	before_action :load_twert, only: [:show]

	def index
	end

	def show
	end

	def create
		twert = Twert.new(twert_params)

		if twert.save
			redirect_to root_path, notice: "Thanks for your thoughts, I'll toss them out into the wide open ocean polluted with other meaningless thought bottles"
		else
			render :index, notice: "Try again, friend-o"
		end
	end

	def twert_params
		params.require(:twert).permit(:content, :parent_twert_id).merge(user: current_user)
	end

	helper_method def hot_twerts
		Twert.last(10)
	end

	helper_method def twert
		@_twert ||= Twert.find_by(id: params[:id])
	end

	private

	def load_twert
		unless (twert)
			redirect_to root_path, notice: "Sorry, we couldn't find that twert"
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end

    def create
        @user = User.new(user_params)

        #user.valid?
        if @user.save
            redirect_to root_path, notice: "You done it, #{@user.lastname}"
        else
            render :signup#, notice: "you screwed up"
        end
    end

    def signup
        @user = User.new
    end

    private

    def user_params
        params.require(:user).permit(:username, :firstname, :lastname, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twerty</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice].present? %>
      <%= flash[:notice] %>
    <% end %>
    <%= yield %>
  </body>

</html>

app/views/likes/_like_button.html.erb
<%= content_tag(:span, "#{likeable.likes.count} likes", id: "like_count_#{likeable_html_id(likeable)}" ) %>

<%= button_tag "like this dumb thought", id: "like_#{likeable_html_id(likeable)}" %>

<%= javascript_tag do %>
	var like_btn = <%= "like_#{likeable_html_id(likeable)}" %>

	like_btn.onclick = function(){
		const csrfToken = document.querySelector("[name='csrf-token']").content;
		const likeableId = "<%= likeable.id %>";
		const likeableType = "<%= likeable.class %>";
		const data = {
			likeable_id: likeableId,
			likeable_type: likeableType
		}

		fetch("/likes", {
			method: 'POST',
			credentials: 'same-origin',
			headers: {
				"X-CSRF-Token": csrfToken,
				"Content-Type": "application/json"
			},
			body: JSON.stringify( data )
		}).then(response => {
			// TODO: throw an error if we didn't get a good response
			// if (!response.ok) { throw response; }
			return response.json();
		}).then((data) => {
			// TODO: increment like count on front-end with the response.body.like_count
			console.log(data);
		}).catch(error => {
			// TODO: actually handle error, lmao
			console.log("error", error);
		})

	}
<% end %>

app/views/twerts/_twert.html.erb
<div>
	<%= twert.user.username %>
	<%= twert.created_at.strftime('%I:%M%p (%m-%d-%y)') %>
</div>
<div>
	<%= twert.content %>
</div>
<div>
	<%= render partial: "likes/like_button", locals: { likeable: twert } if current_user.present? %>
</div>

app/views/twerts/_twert_form.html.erb
<% parent_twert = local_assigns[:parent_twert] %>

<div>
    <%= form_with model: Twert.new(), url: twerts_path, method: :post do |form| %>
        <%= form.text_field :content, placeholder: "Type your twerty little thoughts here!" %>
        <%= form.hidden_field(:parent_twert_id, value: parent_twert&.id )%>
        <%= form.submit %>
    <% end %>
</div>

app/views/twerts/index.html.erb
<h1>HELLO WELCOME TO TWERTY</h1>
<h3>you want twerts?</h3>

<% if session[:user_id].present? %>
	<%= User.find(session[:user_id]).username%>
<% end %>

<% if current_user.present? %>
	<div>
		<%= "#{current_user.firstname} #{current_user.lastname}" %>
	</div>

	<%= render partial: "twert_form" %>

	<div>
		<%= link_to "The cooler log out \"button\"", logout_path, method: :delete %>
	</div>
<% else %>
	<div>
		<%= link_to "Log in!", login_path %>
	</div>
<% end %>

<div>
	<% hot_twerts.each do |t| %>
		<%= render partial: "twert", locals: { twert: t } %>
		<%= link_to "all replies", twert_path(t) %>
	<% end %>
</div>

app/views/twerts/show.html.erb
<%= render partial: "twert", locals: { twert: twert } %>
<div>
	<% twert.replies.each do |t| %>
		<%= render partial: "twert", locals: { twert: t } %>
	<% end %>
	<%= render partial: "twert_form", locals: { parent_twert: twert } %>
</div>

app/views/users/signup.html.erb
<h1>Howdy doo, fellow stranger! Introduce yerself.</h1>
<%= 'hey there, we\'re on Rails' %>
<%= Rails.version %>
<%= ', just so you can more easily find some exploits on this here app' %>

<%= form_with model: @user, url: signup_path do |form| %>

	<div>
		<%= form.label :username, "Username" %>
		<%= form.text_field :username, value: @user.username %>
	</div>

	<div>
		<%= form.label :firstname, "First name" %>
		<%= form.text_field :firstname, value: @user.firstname %>
	</div>

	<div>
		<%= form.label :lastname, "Last name" %>
		<%= form.text_field :lastname, value: @user.lastname %>
	</div>

	<div>
		<%= form.label :email, "Email" %>
		<%= form.email_field :email, value: @user.email %>
	</div>

	<div>
		<%= form.label :password, "Password" %>
		<%= form.password_field :password %>
	</div>

	<%= form.submit %>
<% end %>

<style>
</style>